language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer require techpivot/phalcon-ci-installer
  - vendor/bin/install-phalcon.sh
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false